version: '3'
services:
  db:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
volumes:
  db_data: